
void  SettingIci_MTZ();
void  SettingIci_UMM();
void  SettingIci_DZ1();
void  SettingIci_DZ2to5();
void  SettingIci_TZNP();
void  SettingIci_NZOP();
void  SettingIci_Rangir();
int isActivCmdDV(int numCmd, int numDV);
int isActivCmdRele(int numCmd, int numRele);
int isActivCmdLed(int numCmd, int numLed);
void SettingIci_RangirMTZ2DV(int nDV);
void SettingIci_RangirMTZ2Rele(int nRele);
void SettingIci_RangirMTZ2Led(int nLed);
void SettingIci_RangirUMM2DV(int nDV);
void SettingIci_RangirUMM2Rele(int nRele);
void SettingIci_RangirUMM2Led(int nLed);
void SettingIci_RangirTZNP2DV(int nDV);
void SettingIci_RangirTZNP2Rele(int nRele);
void SettingIci_RangirTZNP2Led(int nLed);
void SettingIci_RangirDZ1ToDV(int nDV);
void SettingIci_RangirDZ1ToRele(int nRele);
void SettingIci_RangirDZ1ToLed(int nLed);
